// Code generated by ent, DO NOT EDIT.

package ent

import (
	"qn-base/app/admin/internal/data/ent/schema"
	"qn-base/app/admin/internal/data/ent/systemuser"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	systemuserMixin := schema.SystemUser{}.Mixin()
	systemuserMixinFields5 := systemuserMixin[5].Fields()
	_ = systemuserMixinFields5
	systemuserFields := schema.SystemUser{}.Fields()
	_ = systemuserFields
	// systemuserDescTenantID is the schema descriptor for tenant_id field.
	systemuserDescTenantID := systemuserMixinFields5[0].Descriptor()
	// systemuser.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	systemuser.TenantIDValidator = systemuserDescTenantID.Validators[0].(func(string) error)
	// systemuserDescSex is the schema descriptor for sex field.
	systemuserDescSex := systemuserFields[8].Descriptor()
	// systemuser.DefaultSex holds the default value on creation for the sex field.
	systemuser.DefaultSex = systemuserDescSex.Default.(int8)
	// systemuserDescStatus is the schema descriptor for status field.
	systemuserDescStatus := systemuserFields[10].Descriptor()
	// systemuser.DefaultStatus holds the default value on creation for the status field.
	systemuser.DefaultStatus = systemuserDescStatus.Default.(int8)
}
