// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TSystemUserColumns holds the columns for the "t_system_user" table.
	TSystemUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_by", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "update_by", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_id", Type: field.TypeString, Unique: true},
		{Name: "account", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "nickname", Type: field.TypeString, Nullable: true},
		{Name: "remark", Type: field.TypeString, Nullable: true},
		{Name: "dept_id", Type: field.TypeInt64, Nullable: true},
		{Name: "post_ids", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "mobile", Type: field.TypeString, Nullable: true},
		{Name: "sex", Type: field.TypeInt8, Nullable: true, Default: 0},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeInt8, Nullable: true, Default: 1},
		{Name: "login_ip", Type: field.TypeString, Nullable: true},
		{Name: "login_date", Type: field.TypeTime, Nullable: true},
	}
	// TSystemUserTable holds the schema information for the "t_system_user" table.
	TSystemUserTable = &schema.Table{
		Name:       "t_system_user",
		Columns:    TSystemUserColumns,
		PrimaryKey: []*schema.Column{TSystemUserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "systemuser_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{TSystemUserColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TSystemUserTable,
	}
)

func init() {
	TSystemUserTable.Annotation = &entsql.Annotation{
		Table: "t_system_user",
	}
}
