// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: conf/conf-demo.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Demo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Some          *Some                  `protobuf:"bytes,1,opt,name=some,proto3" json:"some,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demo) Reset() {
	*x = Demo{}
	mi := &file_conf_conf_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demo) ProtoMessage() {}

func (x *Demo) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demo.ProtoReflect.Descriptor instead.
func (*Demo) Descriptor() ([]byte, []int) {
	return file_conf_conf_demo_proto_rawDescGZIP(), []int{0}
}

func (x *Demo) GetSome() *Some {
	if x != nil {
		return x.Some
	}
	return nil
}

type Some struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thing         string                 `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Some) Reset() {
	*x = Some{}
	mi := &file_conf_conf_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Some) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Some) ProtoMessage() {}

func (x *Some) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Some.ProtoReflect.Descriptor instead.
func (*Some) Descriptor() ([]byte, []int) {
	return file_conf_conf_demo_proto_rawDescGZIP(), []int{1}
}

func (x *Some) GetThing() string {
	if x != nil {
		return x.Thing
	}
	return ""
}

var File_conf_conf_demo_proto protoreflect.FileDescriptor

const file_conf_conf_demo_proto_rawDesc = "" +
	"\n" +
	"\x14conf/conf-demo.proto\x12\n" +
	"kratos.api\",\n" +
	"\x04Demo\x12$\n" +
	"\x04some\x18\x01 \x01(\v2\x10.kratos.api.SomeR\x04some\"\x1c\n" +
	"\x04Some\x12\x14\n" +
	"\x05thing\x18\x01 \x01(\tR\x05thingB\x18Z\x16kva/internal/conf;confb\x06proto3"

var (
	file_conf_conf_demo_proto_rawDescOnce sync.Once
	file_conf_conf_demo_proto_rawDescData []byte
)

func file_conf_conf_demo_proto_rawDescGZIP() []byte {
	file_conf_conf_demo_proto_rawDescOnce.Do(func() {
		file_conf_conf_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_demo_proto_rawDesc), len(file_conf_conf_demo_proto_rawDesc)))
	})
	return file_conf_conf_demo_proto_rawDescData
}

var file_conf_conf_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_conf_conf_demo_proto_goTypes = []any{
	(*Demo)(nil), // 0: kratos.api.Demo
	(*Some)(nil), // 1: kratos.api.Some
}
var file_conf_conf_demo_proto_depIdxs = []int32{
	1, // 0: kratos.api.Demo.some:type_name -> kratos.api.Some
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_conf_conf_demo_proto_init() }
func file_conf_conf_demo_proto_init() {
	if File_conf_conf_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_demo_proto_rawDesc), len(file_conf_conf_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_demo_proto_goTypes,
		DependencyIndexes: file_conf_conf_demo_proto_depIdxs,
		MessageInfos:      file_conf_conf_demo_proto_msgTypes,
	}.Build()
	File_conf_conf_demo_proto = out.File
	file_conf_conf_demo_proto_goTypes = nil
	file_conf_conf_demo_proto_depIdxs = nil
}
