// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SystemUser is the predicate function for systemuser builders.
type SystemUser func(*sql.Selector)
